/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Game from "./script/Game"
import Ball from "./script/Ball"
import GameControl from "./script/GameControl"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1136;
    static height:number=640;
    static scaleMode:string="fixedauto";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="game/Game.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/Game.ts",Game);
        reg("script/Ball.ts",Ball);
        reg("script/GameControl.ts",GameControl);
    }
}
GameConfig.init();